name: My First CI Pipeline

on: 
  push: 
    branches: 
      - main 


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository 
        uses: actions/checkout@v6
        
      - name: set up python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: check python version
        run: python --version

      - name: install dependencies
        run: pip install -r requirements-dev.txt

      - name: run tests
        run: pytest
        
