name: My First CI Pipeline

on: 
  push: 
    branches: 
      - main 


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository 
        uses: actions/checkout@v6
        
      - name: set up python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: check python version
        run: python --version

      - name: install dependencies
        run: pip install -r requirements-dev.txt

      - name: run tests
        run: pytest

      - name: run linting
        run: ruff check . 

  deploy: 
    needs: test
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    steps:
      - name: azure login
        uses: azure/login@v2
        with:
          client-ID: ${{secrets.AZURE_CLIENT_ID }}
          tenant-ID: ${{ secrets.AZURE_TENANT_ID }}
          subscription-ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          run: echo "Login worked— deployment can proceed!"
